[package]
name = "gupi-screen-capture"
version.workspace = true
edition = "2024"
license = "MIT"
publish = false

[dependencies]
gpui-kit.workspace = true
smol = "2.0.2"
thiserror = "2.0.18"
image = { version = "0.25.10", default-features = false, features = ["png"] }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
xcap = "0.9.8"
platform-ext.workspace = true
window-ext.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-graphics = { version = "0.3.2", default-features = false, features = ["CGWindow"] }
